In [2]:
import keras
import numpy as np

In [16]:
data_in = np.array([[0,0],[0,1],[1,0],[1,1]])

print("data in \n", data_in)

logic_and = np.array([[0],[0],[0],[1]])
print("\nlogic_and \n", logic_and)

logic_or = np.array([[0],[1],[1],[1]])
print("\nlogic_or \n", logic_or)

logic_xor = np.array([[0],[1],[1],[0]])
print("\nlogic_xor \n", logic_xor)

data in 
 [[0 0]
 [0 1]
 [1 0]
 [1 1]]

logic_and 
 [[0]
 [0]
 [0]
 [1]]

logic_or 
 [[0]
 [1]
 [1]
 [1]]

logic_or 
 [[0]
 [1]
 [1]
 [1]]


In [8]:
model = keras.models.Sequential()

[[0]
 [0]
 [0]
 [1]]
