In [2]:
import keras
import numpy as np

Using TensorFlow backend.


In [3]:
data_in = np.array([[0,0],[0,1],[1,0],[1,1]])

print("data_in \n", data_in)

logic_and = np.array([[0],[0],[0],[1]])
print("\nlogic_and \n", logic_and)

logic_or = np.array([[0],[1],[1],[1]])
print("\nlogic_or \n", logic_or)

logic_xor = np.array([[0],[1],[1],[0]])
print("\nlogic_xor \n", logic_xor)

data in 
 [[0 0]
 [0 1]
 [1 0]
 [1 1]]

logic_and 
 [[0]
 [0]
 [0]
 [1]]

logic_or 
 [[0]
 [1]
 [1]
 [1]]

logic_xor 
 [[0]
 [1]
 [1]
 [0]]


In [59]:
model = keras.models.Sequential(layers=[
    keras.layers.Dense(input_dim=2, units=2),
    keras.layers.Activation(keras.activations.sigmoid),
    keras.layers.Dense(units=1),
    keras.layers.Activation(keras.activations.sigmoid)
])

model.compile(optimizer=keras.optimizers.SGD(lr=.5), loss='mse')

In [61]:
model.weights

[<tf.Variable 'dense_5/kernel:0' shape=(2, 2) dtype=float32_ref>,
 <tf.Variable 'dense_5/bias:0' shape=(2,) dtype=float32_ref>,
 <tf.Variable 'dense_6/kernel:0' shape=(2, 1) dtype=float32_ref>,
 <tf.Variable 'dense_6/bias:0' shape=(1,) dtype=float32_ref>]

In [68]:
keras.backend.eval(model.weights[0])

array([[ 1.07196319,  0.99184239],
       [ 0.39306819,  0.44276404]], dtype=float32)

In [73]:
model.fit(data_in, logic_xor, epochs=1000, verbose = False)

In [79]:
model.predict(np.array([[1,1]]))

array([[ 0.06794927]], dtype=float32)